### PR TITLE
Feature/advantages

### PR DESCRIPTION
**Pull request by grzesiekcz**
Finished sections advantages and gallery for desktop, tablet and mobile

### CODE REVIEW

**Comment by MonikaJablonska** [comment]
Test

**Review by Jaciubek — COMMENTED** [review]
w porządku

**Comment by MonikaJablonska** [comment]
@Jaciubek Please use follow the instruction to approve the review:
https://htmlcssplon4.slack.com/archives/C036VJ59X6H/p1647617305426499 
and let me know on slack when it will be finished :)

**Review by Jaciubek — APPROVED** [review]
wszystko ok

**Review by MonikaJablonska — APPROVED** [review]

**Pull request merged**
